'use client';
import { useEffect, useState } from 'react';
import { adminApi } from '@/lib/api/admin';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Button } from '@/components/ui/button';
type Scenario = { id: string; slug: string; title: string; setting: string; ai_role: string; learner_role: string; cefr_level: string; goal: string; target_vocab: string[]; opening_line: string; persona_name?: string; persona_backstory?: string };
const empty: Omit<Scenario,'id'> = {slug:'',title:'',setting:'',ai_role:'',learner_role:'',cefr_level:'A1',goal:'',target_vocab:[],opening_line:'',persona_name:'',persona_backstory:''};
export default function AiScenariosPage(){const [items,setItems]=useState<Scenario[]>([]);const [form,setForm]=useState<any>(empty);const [message,setMessage]=useState(''); const load=async()=>setItems(await adminApi.listAiScenarios()); useEffect(()=>{void load()},[]); const save=async()=>{const p={...form,target_vocab:typeof form.target_vocab==='string'?form.target_vocab.split(',').map((x:string)=>x.trim()).filter(Boolean):form.target_vocab}; if(form.id) await adminApi.updateAiScenario(form.id,p); else await adminApi.createAiScenario(p); setMessage('Scenario saved.'); setForm(empty); await load();}; const field=(key:string,label:string,multi=false)=>(multi?<Textarea value={form[key]??''} onChange={e=>setForm({...form,[key]:e.target.value})} placeholder={label}/>:<Input value={form[key]??''} onChange={e=>setForm({...form,[key]:e.target.value})} placeholder={label}/>); return <div className="max-w-5xl space-y-6"><div><h1 className="text-2xl font-bold">AI Scenarios</h1><p className="text-text-muted">Create role-play scenarios and persona backstories.</p></div><Card><CardHeader><CardTitle>{form.id?'Edit scenario':'New scenario'}</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-2">{field('slug','Slug')}{field('title','Title')}{field('setting','Setting',true)}{field('ai_role','AI role')}{field('learner_role','Learner role')}{field('cefr_level','CEFR level')}{field('goal','Mini-goal',true)}{field('target_vocab','Target vocabulary, comma separated')}{field('opening_line','Opening line',true)}{field('persona_name','Persona name')}{field('persona_backstory','Persona backstory',true)}<div className="md:col-span-2"><Button onClick={save}>Save scenario</Button>{message&&<span className="ml-3 text-sm text-success">{message}</span>}</div></CardContent></Card><div className="space-y-3">{items.map(s=><Card key={s.id}><CardContent className="flex items-center justify-between gap-4 py-4"><div><strong>{s.title}</strong><p className="text-sm text-text-muted">{s.cefr_level} · {s.setting} · {s.persona_name||'No persona'}</p></div><Button variant="outline" onClick={()=>setForm({...s,target_vocab:s.target_vocab.join(', ')})}>Edit</Button></CardContent></Card>)}</div></div>}
